### PR TITLE
210310_Deepanshu Assignment 1

### PR DESCRIPTION
**Pull request by Deepanshu18099**

### CODE REVIEW

**Comment by Pranshu-Gaur** [comment]
Good work for assignment 1, it would have been great if you would have continued.

**Comment by Deepanshu18099** [comment]
I have participated in code forces contest also I have tried assignment 2
(was not able to complete that) so I didn't submitted and did not continue.
Do I please have any chance of ratification if I complete my 2nd assignment.
Thankyou,
Deepanshu

**Comment by Pranshu-Gaur** [comment]
If you submit assignment 2,( do it as much as you can), then you may be ratified. Always remember, incomplete submission is better than no submission. Just don't give up easily.

**Comment by Deepanshu18099** [comment]
*Thanks Pranshu*,
I have tried assignment 2 as much I can from yesterday. It's almost
complete and have created a pull request.
Can you confirm my submission?

**Pull request merged**
